[package]
name = "me"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
webrtc = "0.7.2"
tokio = { version = "1.15.0", features = ["full"] }
tokio-util = "0.7.8"
